name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.0
      with:
        # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
        java-version: 1.8
        # The package type (jre, jdk, jdk+fx)
        java-package: jdk
        # The architecture (x86, x64) of the package.
        architecture: x86

    - name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.0.7

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with gradlew
      run: ./gradlew assembleDebug

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: app/build/outputs/apk/debug/*.apk
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
